services:
  redis-node-1:
    image: redis:7.2-alpine
    container_name: redis-node-1
    ports:
      - "127.0.0.1:7001:6379"
    networks:
      - redis-cluster-net
    command: redis-server --cluster-enabled yes --cluster-config-file nodes-node-1.conf --cluster-node-timeout 5000 --appendonly yes
  
  redis-node-2:
    image: redis:7.2-alpine
    container_name: redis-node-2
    ports:
      - "127.0.0.1:7002:6379"
    networks:
      - redis-cluster-net
    command: redis-server --cluster-enabled yes --cluster-config-file nodes-node-2.conf --cluster-node-timeout 5000 --appendonly yes

  redis-node-3:
    image: redis:7.2-alpine
    container_name: redis-node-3
    ports:
      - "127.0.0.1:7003:6379"
    networks:
      - redis-cluster-net
    command: redis-server --cluster-enabled yes --cluster-config-file nodes-node-3.conf --cluster-node-timeout 5000 --appendonly yes

  redis-node-4:
    image: redis:7.2-alpine
    container_name: redis-node-4
    ports:
      - "127.0.0.1:7004:6379"
    networks:
      - redis-cluster-net
    command: redis-server --cluster-enabled yes --cluster-config-file nodes-node-4.conf --cluster-node-timeout 5000 --appendonly yes

  redis-node-5:
    image: redis:7.2-alpine
    container_name: redis-node-5
    ports:
      - "127.0.0.1:7005:6379"
    networks:
      - redis-cluster-net
    command: redis-server --cluster-enabled yes --cluster-config-file nodes-node-5.conf --cluster-node-timeout 5000 --appendonly yes

  redis-node-6:
    image: redis:7.2-alpine
    container_name: redis-node-6
    ports:
      - "127.0.0.1:7006:6379"
    networks:
      - redis-cluster-net
    command: redis-server --cluster-enabled yes --cluster-config-file nodes-node-6.conf --cluster-node-timeout 5000 --appendonly yes

networks:
  redis-cluster-net:
    external: true