// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Product struct {
	ID          int32
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type ProductCategory struct {
	ProductID  int32
	CategoryID int32
}

type ProductVariant struct {
	ID        int32
	ProductID int32
	Color     string
	Size      string
	Quantity  int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
