// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: product_variant.sql

package sqlc

import (
	"context"
)

const insertProductVariant = `-- name: InsertProductVariant :one
INSERT INTO product_variants (product_id, color, size, quantity) VALUES ($1, $2, $3, $4) RETURNING color, size, quantity
`

type InsertProductVariantParams struct {
	ProductID int32
	Color     string
	Size      string
	Quantity  int32
}

type InsertProductVariantRow struct {
	Color    string
	Size     string
	Quantity int32
}

func (q *Queries) InsertProductVariant(ctx context.Context, arg InsertProductVariantParams) (InsertProductVariantRow, error) {
	row := q.db.QueryRow(ctx, insertProductVariant,
		arg.ProductID,
		arg.Color,
		arg.Size,
		arg.Quantity,
	)
	var i InsertProductVariantRow
	err := row.Scan(&i.Color, &i.Size, &i.Quantity)
	return i, err
}
