// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: product_category.sql

package sqlc

import (
	"context"
)

const insertProductCategory = `-- name: InsertProductCategory :exec
INSERT INTO product_categories (product_id, category_id) VALUES ($1, $2)
`

type InsertProductCategoryParams struct {
	ProductID  int32
	CategoryID int32
}

func (q *Queries) InsertProductCategory(ctx context.Context, arg InsertProductCategoryParams) error {
	_, err := q.db.Exec(ctx, insertProductCategory, arg.ProductID, arg.CategoryID)
	return err
}
